### ISSUE TITLE
Netsniff.js Example

### ISSUE THREAD

**Issue by ndrut** [alexscheelmeyer/node-phantom#14]
With your module on nodejs, I'm trying to use the HAR Exporting example on the main phantomjs repo: https://github.com/ariya/phantomjs/blob/master/examples/netsniff.js

I'm encountering issues regarding Date objects. I've combined performing the render aswell as the HAR exporter in one action:

``` javascript
       phantom.create(function (error, ph){
                return ph.createPage(function (err, page){
                        page.address = final.url;
                        page.resources = [];
                        page.onLoadStarted = function () {
                                 page.startTime = new Date();
                                console.log(page.startTime);
                         };
                        page.onResourceRequested = function (req) {
                                page.resources[req.id] = {
                                request: req,
                                startReply: null,
                                endReply: null
                                };
                                //console.log(page.resources);
                        };
                        page.onResourceReceived = function (res) {
                                if (res.stage === 'start') {
                                        page.resources[res.id].startReply = res;
                                //      console.log(res);
                                 }
                                if (res.stage === 'end') {
                                        page.resources[res.id].endReply = res;
                                //      console.log(res);
                                 }
                        };
                        page.set('viewportSize', { width: 1024, height: 768 });
                        return page.open(final.url, function (error, stat){
                                        var har;
                                        page.title = page.evaluate(function () {
                                        return document.title;
                                         });
                                        final.har = { 'onInputData': null };
                                        har = createHAR(page.address, page.title, page.startTime, page.resources);
                                        final.har.onInputData = JSON.stringify(har, undefined, 4);
                                        page.endTime = new Date();
                                        final.path = '/home/myprop/public_html/assets/i/' + final.truedomain;
                                        var now = Date.now();
                                        final.fullpath = final.path + '/' + now + '.png';
                                        final.thumbpath = final.path + '/' + now + 'thumb.png';
                                        fs.mkdir( final.path, 0755, function (err) {
                                                page.render( final.fullpath , function(err) {
                                                        gm(final.fullpath).thumb(150, 150, final.thumbpath, 50, function(err){
                                                                if(err) return console.dir(arguments)
                                                                callback(final);
                                                                ph.exit();
                                        });
                                        });
                                        });
                });
```

When I execute the request, it's erroring with:

```
/home/api/Andrew.js:278
            startedDateTime: request.time.toISOstring(),
                                          ^
TypeError: Object 2012-11-09T05:36:17.385Z has no method 'toISOstring'
    at /home/api/Andrew.js:278:43
    at Array.forEach (native)
    at createHAR (/home/api/Andrew.js:268:15)
    at Object.exports.scan [as cb] (/home/api/Andrew.js:240:13)
    at Socket.module.exports.create.io.sockets.on.socket.on.id (/home/api/node_modules/node-phantom/node-phantom.js:114:19)
    at Socket.EventEmitter.emit [as $emit] (events.js:93:17)
    at SocketNamespace.handlePacket (/home/api/node_modules/node-phantom/node_modules/socket.io/lib/namespace.js:335:22)
    at Manager.onClientMessage (/home/api/node_modules/node-phantom/node_modules/socket.io/lib/manager.js:487:38)
    at WebSocket.Transport.onMessage (/home/api/node_modules/node-phantom/node_modules/socket.io/lib/transport.js:387:20)
    at Parser.<anonymous> (/home/api/node_modules/node-phantom/node_modules/socket.io/lib/transports/websocket/default.js:36:10)
```

That function is what's provided with the phantomjs example and does work correctly. Why I believe it's relevant to ask here, is because I don't think the objects I'm setting up are getting passed or executed:

``` javascipt
                        page.onLoadStarted = function () {
                                 page.startTime = new Date();
                                console.log(page.startTime);
                         };
                        page.onResourceRequested = function (req) {
                                page.resources[req.id] = {
                                request: req,
                                startReply: null,
                                endReply: null
                                };
                                //console.log(page.resources);
                        };
                        page.onResourceReceived = function (res) {
                                if (res.stage === 'start') {
                                        page.resources[res.id].startReply = res;
                                //      console.log(res);
                                 }
                                if (res.stage === 'end') {
                                        page.resources[res.id].endReply = res;
                                //      console.log(res);
                                 }
                        };
```

Any help would be much appreciated.

**Comment by alexscheelmeyer** [comment]
Yeah, these callbacks were not previously implemented but are now supported through the changes in pull request #5.
