### ISSUE TITLE
TypeError: Property 'cb' of object #<Object> is not a function

### ISSUE THREAD

**Issue by holms** [alexscheelmeyer/node-phantom#99]
First try, and first issue:

Here's a script:

```
var phantom = require('node-phantom')

var Log = require('log')
log = new Log('info');


phantom.create(function(err,ph) {
  return ph.createPage(function(err,page) {

    /*
    page.onResourceRequested = function(request) {
      console.log('Request ' + JSON.stringify(request, undefined, 4));
    }
    page.onResourceReceived = function(response) {
      console.log('Receive ' + JSON.stringify(response, undefined, 4));
    }
    */
    url = "http://google.com"
    page.open(url, function(err,status) {
        if (status !== "success") {
            log.error("Unable to access network"); return
        }
        page.viewportSize = { width: 1024, height: 768 }
        page.render("./thumbie.jpg", { format: 'jpg', quality: 80 })
    })

  })
})
```

Here's an error:

```
$ node app.js
/home/thumbnailer/app/node_modules/node-phantom/node-phantom.js:178
                                                        cmds[cmdId].cb(null);
                                                                    ^
TypeError: Property 'cb' of object #<Object> is not a function
    at Socket.<anonymous> (/home/thumbnailer/app/node_modules/node-phantom/node-phantom.js:178:20)
    at Socket.EventEmitter.emit [as $emit] (events.js:95:17)
    at SocketNamespace.handlePacket (/home/thumbnailer/app/node_modules/node-phantom/node_modules/socket.io/lib/namespace.js:335:22)
    at Manager.onClientMessage (/home/thumbnailer/app/node_modules/node-phantom/node_modules/socket.io/lib/manager.js:488:38)
    at WebSocket.Transport.onMessage (/home/thumbnailer/app/node_modules/node-phantom/node_modules/socket.io/lib/transport.js:387:20)
    at Parser.<anonymous> (/home/thumbnailer/app/node_modules/node-phantom/node_modules/socket.io/lib/transports/websocket/default.js:36:10)
    at Parser.EventEmitter.emit (events.js:95:17)
    at Parser.parse (/home/thumbnailer/app/node_modules/node-phantom/node_modules/socket.io/lib/transports/websocket/default.js:343:12)
    at Parser.parse (/home/thumbnailer/app/node_modules/node-phantom/node_modules/socket.io/lib/transports/websocket/default.js:346:19)
    at Parser.add (/home/thumbnailer/app/node_modules/node-phantom/node_modules/socket.io/lib/transports/websocket/default.js:315:8)
```

**Comment by holms** [comment]
seems to be someone had same problem in another phantom.js bridge: https://github.com/sgentle/phantomjs-node/issues/154

**Comment by ashishtilara** [comment]
+1
